apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportevents-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportevents
  template:
    metadata:
      labels:
        app: sportevents
    spec:
      containers:
        - name: sportevents
          image: davidom582/sportevents:latest
---
apiVersion: v1
kind: Service
metadata:
  name: sportevents-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: sportevents
  ports:
  - name: sportevents
    protocol: TCP
    port: 80
      
